"""add phase_name to timeline_nodes

Revision ID: fa54caecf7c9
Revises: 6742430d2911
Create Date: 2026-03-01 09:27:26.153037

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fa54caecf7c9"
down_revision: str | Sequence[str] | None = "6742430d2911"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("timeline_nodes", sa.Column("phase_name", sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("timeline_nodes", "phase_name")
    # ### end Alembic commands ###
